os: linux
dist: focal # 20.04 LTS
sudo: false

language: node_js
node_js:
  - 14

install:
  - npm ci

jobs:
  include:
    - stage: Commit lint
      script: ./node_modules/.bin/commitlint --from $(git merge-base --fork-point master) --verbose
    - stage: Lint
      script: npm run lint
    - stage: Test
      script: npm test
      after_script: npm run codecov
