os: linux
dist: focal # 20.04 LTS
sudo: false

language: node_js
node_js:
  - 12
  - 14

install:
  - npm ci

jobs:
  include:
    - stage: Lint
      script: npm run lint
    - stage: Test
      script:
      - npm test
      - npm run codecov
