export const AMQP_CONNECTION_RECONNECT = 'AMQP_CONNECTION_RECONNECT';

export const AMQP_CLIENT_TOKEN = 'AMQP_CLIENT';
export const AMQP_DEFAULT_CONNECTION_TOKEN = 'AMQP_DEFAULT_CONNECTION';
export const AMQP_CONNECTION_OPTIONS_TOKEN = 'AMQP_CONNECTION_OPTIONS';
