name: Pull request

on: [pull_request, pull_request_target]

permissions:
  checks: write
  contents: write

jobs:
  continuous-integration:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
      - name: Install NPM dependencies
        run: npm ci
      - name: Commit lint
        run: ./node_modules/.bin/commitlint --from $(git merge-base --fork-point master) --verbose
      - name: Lint
        run: npm run lint
      - name: Lint
        uses: wearerequired/lint-action@v2.3.0
        with:
          continue_on_error: false
          auto_fix: false
          neutral_check_on_warning: false
          eslint: true
          eslint_args: src/**/*.ts
          eslint_extensions: ts
          prettier: true
          prettier_args: src/**/*.ts
          prettier_extensions: ts
      - name: Test
        run: |
          npm test
          npm run codecov
