name: Pull request

on: [pull_request_target]

permissions:
  checks: write
  contents: write

jobs:
  continuous-integration:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'
      - name: Install NPM dependencies
        run: npm ci
      - name: Commit lint
        run: ./node_modules/.bin/commitlint --from $(git merge-base --fork-point main) --verbose
      - name: Eslint
        run: npm run lint
      - name: Test
        run: |
          npm run test:cov
