name: Pull request

on: [pull_request]

jobs:
  continuous-integration:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'
      - name: Install NPM dependencies
        run: npm ci
      - name: Commit lint
        run: ./node_modules/.bin/commitlint --from $(git merge-base --fork-point master) --verbose
      - name: Lint
        run: npm run lint
      - name: Lint
        uses: wearerequired/lint-action@v1.10.0
        with:
          continue_on_error: false
          auto_fix: false
          neutral_check_on_warning: false
          eslint: true
          eslint_args: src/**/*.ts
          eslint_extensions: ts
          prettier: true
      - name: Test
        run: |
          npm test
          npm run codecov
